ipynb extension can be used to open a python notebook file.

In [ ]:
import numpy as np

np.zeros(3) # Array of 3 zeros

array([[1., 1.]])

In [ ]:
np.ones((3,2)) # 2D array. Input is a tuple

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.array([1, 2, 3])

array([1, 2, 3])

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr.shape

(2, 3)

In [ ]:
arr.shape = (3,2) # Tuple
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
other_array = np.linspace(1,5,4) # Print 4 values in range of 1 - 4.
print(other_array)

[1.         2.33333333 3.66666667 5.        ]


In [ ]:
simple_array = np.array([1, 2, 3])
print(simple_array + 2)

[3 4 5]


In [25]:
simple_array * 5

array([ 5, 10, 15])

In [26]:
simple_array * simple_array

array([1, 4, 9])

In [27]:
simple_array @ simple_array # Dot product of 2 arrays. (1*1) + (2*2) + (3*3)

14

In [ ]:
# Other Functions
print("Sum: ",np.sum(simple_array))
print("Mean: ",np.mean(simple_array))
print("Std: ",np.std(simple_array))
print("Min: ", np.min(simple_array))
print("Max: ", np.max(simple_array))
print("ArgMin: ", np.argmin(simple_array))
print("ArgMax: ", np.argmax(simple_array)) # Position with highest value printed

Sum:  6
Mean:  2.0
Std:  0.816496580927726
Min:  1
Max:  3
ArgMin:  0
ArgMax:  2


In [36]:
# Comparison
simple_array < 3

array([ True,  True, False])

In [ ]:
np.where(simple_array < 3, 10, 0) # If simple_array < 3, set 10 to True values and 0 to False values.


array([10, 10,  0])

In [ ]:
simple_array[:2] # Prints first 2 elements from the start

array([1, 2])